(async function(){
'use strict';
const $=s=>document.querySelector(s),{client,escape:esc,safeImage}=window.CatalogBackend,cart=new Map();let products=[],shop=window.SHOP,category='全部商品',timer,cloudReady=false,refreshing=null;
const money=n=>'NT$ '+n.toLocaleString('zh-TW'),find=id=>products.find(p=>p.id===id);
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function openDialog(id){document.getElementById(id).showModal()}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
function categories(){const names=['全部商品',...new Set(products.map(p=>p.category))];if(!names.includes(category))category=names[0];$('#categories').innerHTML=names.map(n=>`<button class="chip ${category===n?'active':''}" aria-pressed="${category===n}" data-cat="${esc(n)}">${esc(n)}</button>`).join('');$('#categories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.cat;categories();render()})}
function render(){const q=$('#search').value.trim().toLowerCase();let list=products.filter(p=>(category==='全部商品'||p.category===category)&&[p.name,p.category,p.spec,p.id].join(' ').toLowerCase().includes(q));if($('#sort').value!=='default')list.sort((a,b)=>$('#sort').value==='low'?a.price-b.price:b.price-a.price);$('#results').textContent=`${list.length} 件商品`;$('#no-results').hidden=!!list.length;$('#no-results').textContent=products.length?'找不到符合的商品，試試其他關鍵字或分類。':'目前尚無可顯示的商品。';$('#grid').innerHTML=list.map(p=>`<article class="card"><button class="photo" data-detail="${esc(p.id)}" aria-label="查看${esc(p.name)}詳情"><img src="${esc(safeImage(p.image))}" alt="${esc(p.name)}" loading="lazy">${p.tag?`<span class="tag">${esc(p.tag)}</span>`:''}${!p.stock?'<span class="sold">暫時缺貨</span>':''}<span class="photo-more">查看商品 ↗</span></button><div class="product-meta"><span>${esc(p.category)}</span><span>${p.stock?'現貨 '+p.stock+' 件':'補貨中'}</span></div><button class="product-name" data-detail="${esc(p.id)}">${esc(p.name)}</button><p class="spec">${esc(p.spec)}</p><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add" data-add="${esc(p.id)}" ${p.stock?'':'disabled'} aria-label="加入${esc(p.name)}至詢價清單">${p.stock?'＋ 加入清單':'暫時缺貨'}</button></div></article>`).join('');$('#grid').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));$('#grid').querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail))}
function add(id,qty=1){const p=find(id);if(!p)return;const next=(cart.get(id)||0)+qty;if(!Number.isInteger(qty)||qty<1||next>p.stock){toast('已達商品可詢價數量上限');return}cart.set(id,next);updateCart();toast(`已加入 ${p.name} × ${qty}`)}
function detail(id){const p=find(id);if(!p)return;$('#detail-content').innerHTML=`<img src="${esc(safeImage(p.image))}" alt="${esc(p.name)}"><div class="detail-text"><p class="eyebrow">${esc(p.category)} / ${esc(p.id)}</p><h2>${esc(p.name)}</h2><p>${esc(p.desc)}</p><p class="spec">${esc(p.spec)}</p><strong class="detail-price">${money(p.price)}</strong><p>${p.stock?'現貨 '+p.stock+' 件':'目前缺貨'}</p>${shop.demoMode?'<p class="small">示範商品，圖片僅供示意。</p>':''}<label>詢價數量 <input id="detail-qty" type="number" min="1" max="${p.stock||1}" value="1" ${p.stock?'':'disabled'}></label><button id="detail-add" class="primary full" ${p.stock?'':'disabled'}>加入詢價清單</button></div>`;$('#detail-add').onclick=()=>add(id,Number($('#detail-qty').value));openDialog('detail')}
function message(){let text='您好，我想詢問以下商品：\n\n',sum=0;for(const[id,n]of cart){const p=find(id);if(!p)continue;sum+=p.price*n;text+=`${p.name}（${p.spec}）\n商品編號：${id}｜${n} 件 × ${money(p.price)} = ${money(p.price*n)}\n\n`}text+=`商品預估合計：${money(sum)}（未含運費）\n請協助確認庫存、運費及最終報價，謝謝！`;if($('#note').value.trim())text+='\n\n備註：'+$('#note').value.trim();return text}
function updateCart(){let count=0,sum=0;for(const[id,n]of cart){const p=find(id);if(p){count+=n;sum+=p.price*n}}$('#count').textContent=count;$('#cart-summary').hidden=!count;$('#cart-items').innerHTML=count?[...cart].map(([id,n])=>{const p=find(id);if(!p)return '';return `<div class="cart-item"><img src="${esc(safeImage(p.image))}" alt=""><div><h3>${esc(p.name)}</h3><p class="small">${esc(p.spec)}</p><strong>${money(p.price*n)}</strong><div class="qty"><button data-step="-1" data-id="${esc(id)}" aria-label="減少${esc(p.name)}數量" ${n===1?'disabled':''}>−</button><input aria-label="${esc(p.name)}數量" type="number" min="1" max="${p.stock}" value="${n}" data-qty="${esc(id)}"><button data-step="1" data-id="${esc(id)}" aria-label="增加${esc(p.name)}數量" ${n===p.stock?'disabled':''}>＋</button><button class="remove" data-remove="${esc(id)}">移除</button></div></div></div>`}).join(''):'<div class="empty"><h3>清單還空著</h3><p>挑選喜歡的商品，開始你的第一份詢價清單。</p></div>';$('#total').textContent=money(sum);$('#message').textContent=message();$('#cart-items').querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{cart.set(b.dataset.id,cart.get(b.dataset.id)+Number(b.dataset.step));updateCart()});$('#cart-items').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.delete(b.dataset.remove);updateCart()});$('#cart-items').querySelectorAll('[data-qty]').forEach(input=>input.onchange=()=>{const p=find(input.dataset.qty),n=Number(input.value);if(!Number.isInteger(n)||n<1||n>p.stock)toast(`請輸入 1 至 ${p.stock} 的整數`);else cart.set(p.id,n);updateCart()});const id=(shop.lineId||'').trim();$('#line').disabled=!id||!count;$('#line-note').textContent=id?'開啟 LINE 後，請確認詢價內容並送出。':'尚未設定店家 LINE 帳號。可先複製詢價清單。'}
function applyShop(){document.title=shop.name+'｜商品詢價';document.querySelectorAll('[data-shop-name]').forEach(el=>el.textContent=shop.name);$('.footer-brand').textContent=shop.name+' / EVERYDAY SELECT';$('.demo').hidden=!shop.demoMode;const hero=products.find(p=>p.id==='CP01')||products[0];$('.feature').hidden=!hero;if(hero){$('#hero-image').src=safeImage(hero.image);$('#hero-image').alt=hero.name}}
function reconcile(old){let changed=false;for(const[id,n]of cart){const p=find(id),prior=old.find(x=>x.id===id);if(!p||!p.stock){cart.delete(id);changed=true}else{if(n>p.stock){cart.set(id,p.stock);changed=true}if(prior&&(prior.price!==p.price||prior.spec!==p.spec||prior.name!==p.name))changed=true}}if(changed)toast('商品資訊已變動，詢價清單已更新，請重新確認數量與金額。');return changed}
async function loadCatalog(initial=false){if(refreshing)return refreshing;refreshing=(async()=>{if(!client){$('#cloud-status').textContent='無法載入商店，請稍後重新整理。';return{ok:false}}try{const[pr,sr]=await Promise.all([client.from('catalog_products').select('*').eq('is_active',true).order('sort_order').order('id'),client.from('catalog_settings').select('*').eq('id',1).single()]);const error=pr.error||sr.error;if(error){if(initial&&['PGRST205','42P01'].includes(error.code)){products=window.PRODUCTS;shop={...window.SHOP,demoMode:true};cloudReady=false;$('#cloud-status').textContent='資料庫尚未啟用，目前顯示示範商品。';applyShop();categories();render();updateCart();return{ok:true,demo:true}}throw error}const old=products;products=pr.data.map(p=>({...p,desc:p.description}));shop={name:sr.data.shop_name,lineId:sr.data.line_id,demoMode:sr.data.demo_mode};cloudReady=true;const changed=reconcile(old);applyShop();categories();render();updateCart();$('#cloud-status').textContent='商品資料已更新';return{ok:true,changed}}catch{$('#cloud-status').textContent=products.length?'暫時無法更新商品，請重新整理後再詢價。':'商品載入失敗，請稍後重新整理。';return{ok:false}}})();try{return await refreshing}finally{refreshing=null}}
$('#cart-top').onclick=async()=>{updateCart();openDialog('cart');if(cloudReady)await loadCatalog()};$('#search').oninput=render;$('#sort').onchange=render;$('#note').oninput=()=>$('#message').textContent=message();
$('#copy').onclick=async()=>{if(cloudReady){const r=await loadCatalog();if(!r.ok||r.changed){toast(r.changed?'清單已更新，請確認後再次複製。':'無法確認最新資料，請稍後再試。');return}}if(!cart.size)return;try{await navigator.clipboard.writeText(message());toast('詢價內容已複製，可貼到 LINE')}catch{const range=document.createRange();$('#message').parentElement.open=true;range.selectNodeContents($('#message'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);toast('請複製已選取的詢價文字')}};
$('#line').onclick=async()=>{if(!shop.lineId||!cart.size)return;const target=window.open('about:blank','_blank');if(!target){toast('瀏覽器阻擋了新視窗，請允許開啟 LINE 或先複製詢價清單。');return}target.opener=null;if(cloudReady){const result=await loadCatalog();if(!result.ok||result.changed||!shop.lineId||!cart.size){target.close();toast(result.changed?'清單已更新，請確認後再次開啟 LINE。':'無法確認最新資料，請稍後再試。');return}}target.location.replace('https://line.me/R/oaMessage/'+encodeURIComponent(shop.lineId.trim())+'/?'+encodeURIComponent(message()))};$('#refresh-products').onclick=()=>loadCatalog(!cloudReady);
categories();render();updateCart();await loadCatalog(true);setInterval(()=>{if(cloudReady&&!document.hidden&&!$('#detail').open&&!$('#cart').open)loadCatalog()},30000);
})();
