const $=s=>document.querySelector(s), products=window.PRODUCTS, cart=new Map();let category='全部商品',timer;
const money=n=>'NT$ '+n.toLocaleString('zh-TW');
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function openDialog(id){document.getElementById(id).showModal()}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
function categories(){const names=['全部商品',...new Set(products.map(p=>p.category))];$('#categories').innerHTML=names.map(n=>`<button class="chip ${category===n?'active':''}" aria-pressed="${category===n}" data-cat="${n}">${n}</button>`).join('');$('#categories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.cat;categories();render()})}
function render(){const q=$('#search').value.trim().toLowerCase();let list=products.filter(p=>(category==='全部商品'||p.category===category)&&[p.name,p.category,p.spec,p.id].join(' ').toLowerCase().includes(q));if($('#sort').value!=='default')list.sort((a,b)=>$('#sort').value==='low'?a.price-b.price:b.price-a.price);$('#results').textContent=`${list.length} 件商品`;$('#no-results').hidden=!!list.length;$('#grid').innerHTML=list.map(p=>`<article class="card"><button class="photo" data-detail="${p.id}" aria-label="查看${p.name}詳情"><img src="${p.image}" alt="${p.name}示意照片" loading="lazy">${p.tag?`<span class="tag">${p.tag}</span>`:''}${!p.stock?'<span class="sold">暫時缺貨</span>':''}<span class="photo-more">查看商品 ↗</span></button><div class="product-meta"><span>${p.category}</span><span>${p.stock?'現貨 '+p.stock+' 件':'補貨中'}</span></div><button class="product-name" data-detail="${p.id}">${p.name}</button><p class="spec">${p.spec}</p><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add" data-add="${p.id}" ${p.stock?'':'disabled'} aria-label="加入${p.name}至詢價清單">${p.stock?'＋ 加入清單':'暫時缺貨'}</button></div></article>`).join('');$('#grid').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));$('#grid').querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail))}
function add(id,qty=1){const p=products.find(p=>p.id===id),next=(cart.get(id)||0)+qty;if(!Number.isInteger(qty)||qty<1||next>p.stock){toast('已達商品可詢價數量上限');return}cart.set(id,next);updateCart();toast(`已加入 ${p.name} × ${qty}`)}
function detail(id){const p=products.find(p=>p.id===id);$('#detail-content').innerHTML=`<img src="${p.image}" alt="${p.name}示意照片"><div class="detail-text"><p class="eyebrow">${p.category} / ${p.id}</p><h2>${p.name}</h2><p>${p.desc}</p><p class="spec">${p.spec}</p><strong class="detail-price">${money(p.price)}</strong><p>${p.stock?'現貨 '+p.stock+' 件':'目前缺貨'}</p><p class="small">示範商品，圖片僅供示意。</p><label>詢價數量 <input id="detail-qty" type="number" min="1" max="${p.stock||1}" value="1" ${p.stock?'':'disabled'}></label><button id="detail-add" class="primary full" ${p.stock?'':'disabled'}>加入詢價清單</button></div>`;$('#detail-add').onclick=()=>add(id,Number($('#detail-qty').value));openDialog('detail')}
function message(){let text=`您好，我想詢問以下商品：\n\n`;let sum=0;for(const [id,n]of cart){const p=products.find(p=>p.id===id);sum+=p.price*n;text+=`${p.name}（${p.spec}）\n商品編號：${id}｜${n} 件 × ${money(p.price)} = ${money(p.price*n)}\n\n`}text+=`商品預估合計：${money(sum)}（未含運費）\n請協助確認庫存、運費及最終報價，謝謝！`;if($('#note').value.trim())text+='\n\n備註：'+$('#note').value.trim();return text}
function updateCart(){let count=0,sum=0;for(const[id,n]of cart){count+=n;sum+=products.find(p=>p.id===id).price*n}$('#count').textContent=count;$('#cart-summary').hidden=!count;$('#cart-items').innerHTML=count?[...cart].map(([id,n])=>{const p=products.find(p=>p.id===id);return `<div class="cart-item"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><p class="small">${p.spec}</p><strong>${money(p.price*n)}</strong><div class="qty"><button data-step="-1" data-id="${id}" aria-label="減少${p.name}數量" ${n===1?'disabled':''}>−</button><input aria-label="${p.name}數量" type="number" min="1" max="${p.stock}" value="${n}" data-qty="${id}"><button data-step="1" data-id="${id}" aria-label="增加${p.name}數量" ${n===p.stock?'disabled':''}>＋</button><button class="remove" data-remove="${id}">移除</button></div></div></div>`}).join(''):'<div class="empty"><h3>清單還空著</h3><p>挑選喜歡的商品，開始你的第一份詢價清單。</p></div>';$('#total').textContent=money(sum);$('#message').textContent=message();$('#cart-items').querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{cart.set(b.dataset.id,cart.get(b.dataset.id)+Number(b.dataset.step));updateCart()});$('#cart-items').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.delete(b.dataset.remove);updateCart()});$('#cart-items').querySelectorAll('[data-qty]').forEach(input=>input.onchange=()=>{const p=products.find(p=>p.id===input.dataset.qty),n=Number(input.value);if(!Number.isInteger(n)||n<1||n>p.stock){toast(`請輸入 1 至 ${p.stock} 的整數`)}else cart.set(p.id,n);updateCart()})}
$('#cart-top').onclick=()=>{updateCart();openDialog('cart')};$('#search').oninput=render;$('#sort').onchange=render;$('#note').oninput=()=>$('#message').textContent=message();
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(message());toast('詢價內容已複製，可貼到 LINE')}catch{const range=document.createRange();$('#message').parentElement.open=true;range.selectNodeContents($('#message'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);toast('請複製已選取的詢價文字')}};
const lineId=window.SHOP.lineId.trim();$('#line').disabled=!lineId;$('#line-note').textContent=lineId?'開啟 LINE 後，請確認詢價內容並送出。':'示範模式：尚未設定店家 LINE 帳號。可先複製清單，體驗完整詢價內容。';$('#line').onclick=()=>{if(lineId&&cart.size)window.open('https://line.me/R/oaMessage/'+encodeURIComponent(lineId)+'/?'+encodeURIComponent(message()),'_blank','noopener,noreferrer')};
$('#hero-image').src=products[1].image;categories();render();updateCart();
