import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;`);
const schema=await readFile('../supabase/schema.sql','utf8');
await db.exec(schema);await db.exec(schema);await db.exec(await readFile('../supabase/seed.sql','utf8'));
const admin='00000000-0000-0000-0000-000000000001',visitor='00000000-0000-0000-0000-000000000002';
await db.exec(`insert into auth.users values ('${admin}'),('${visitor}');insert into catalog_admins(user_id) values('${admin}');update catalog_products set is_active=false where id='NB01';`);
async function as(role,uid=''){await db.exec(`reset role;set request.jwt.claim.sub='${uid}';set role ${role}`)}
await as('anon');assert.equal((await db.query('select * from catalog_products')).rows.length,5);await assert.rejects(db.query('select * from catalog_admins'));await assert.rejects(db.query("update catalog_products set stock=999 where id='CP01'"));assert.equal((await db.query('select * from catalog_settings')).rows.length,1);
await as('authenticated',visitor);assert.equal((await db.query('select * from catalog_admins')).rows.length,0);assert.equal((await db.query("update catalog_products set stock=999 where id='CP01' returning *")).rows.length,0);await assert.rejects(db.query("insert into catalog_products(id,name,category,price)values('BAD','test','test',1)"));await assert.rejects(db.query(`insert into catalog_admins(user_id) values('${visitor}')`));assert.equal((await db.query("update catalog_settings set shop_name='attack' returning *")).rows.length,0);
await as('authenticated',admin);assert.equal((await db.query('select * from catalog_products')).rows.length,6);const old=(await db.query("select version from catalog_products where id='CP01'")).rows[0].version;assert.equal((await db.query("update catalog_products set stock=7 where id='CP01' and version=$1 returning *",[old])).rows[0].stock,7);assert.equal((await db.query("update catalog_products set stock=88 where id='CP01' and version=$1 returning *",[old])).rows.length,0);assert.equal((await db.query("update catalog_settings set shop_name='test' returning *")).rows[0].shop_name,'test');await assert.rejects(db.query("update catalog_products set stock=-1 where id='CP01'"));await assert.rejects(db.query("update catalog_products set image='javascript:alert(1)' where id='CP01'"));await assert.rejects(db.query("delete from catalog_products where id='CP01'"));
await db.close();console.log('PASS: schema repeatability, anon read/write rules, ordinary-user denial, admin writes, version conflicts, validation, no permanent deletion');
