import {JSDOM} from 'jsdom';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base='../';
const sample={id:'P01',name:'測試商品',category:'分類',spec:'規格',description:'描述',price:100,stock:5,image:'images/mug.jpg',tag:'',is_active:true,sort_order:1,version:1};
function mock(){const state={user:null,admin:true,missing:false,fail:false,conflict:false,rows:[structuredClone(sample)],settings:{id:1,shop_name:'雲端商店',line_id:'',demo_mode:false,version:1},writes:0};const auth={getSession:async()=>({data:{session:state.user?{user:state.user}:null}}),signInWithPassword:async()=>{state.user={id:'u1',email:'manager@example.test'};return{data:{user:state.user}}},signOut:async()=>{state.user=null},onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})};const client={auth,from(table){let filters=[],single=false,mode='get',payload;const query={select(){return query},order(){return query},eq(k,v){filters.push([k,v]);return query},single(){single=true;return query},maybeSingle(){single=true;return query},insert(p){mode='insert';payload=p;return query},update(p){mode='update';payload=p;return query},then(resolve,reject){return Promise.resolve().then(()=>{if(state.missing)return{data:null,error:{code:'PGRST205'}};if(state.fail)return{data:null,error:{code:'NETWORK'}};let rows=table==='catalog_products'?state.rows:table==='catalog_settings'?[state.settings]:(state.admin&&state.user?[{user_id:state.user.id}]:[]);let matched=rows.filter(row=>filters.every(([k,v])=>row[k]===v));if(mode==='insert'){state.writes++;const row={...payload,version:1};state.rows.push(row);return{data:[row],error:null}}if(mode==='update'){state.writes++;if(state.conflict)return{data:[],error:null};for(const row of matched)Object.assign(row,payload,{version:row.version+1});return{data:structuredClone(matched),error:null}}return{data:single?(structuredClone(matched[0])||null):structuredClone(matched),error:null}}).then(resolve,reject)}};return query}};return{state,client}}
async function setup(file,m){const html=await readFile(base+file,'utf8');const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.supabase={createClient:()=>m.client};w.SUPABASE_CONFIG={url:'https://example.test',publishableKey:'test'};w.eval(await readFile(base+'backend.js','utf8'));if(file==='index.html')w.eval(await readFile(base+'products.js','utf8'));w.eval(await readFile(base+(file==='index.html'?'app.js':'admin.js'),'utf8'));return dom}
async function wait(check){for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,5))}throw Error('condition timed out')}
function submit(w,id){w.document.querySelector(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}))}
let m=mock(),dom=await setup('admin.html',m),w=dom.window,d=w.document;await wait(()=>!d.querySelector('#login-panel').hidden);assert(d.querySelector('#workspace').hidden);d.querySelector('[name=email]').value='manager@example.test';d.querySelector('[name=password]').value='test-not-a-real-password';submit(w,'#login-form');await wait(()=>!d.querySelector('#workspace').hidden);assert.equal(d.querySelector('#stat-total').textContent,'1');d.querySelector('#new-product').click();const f=d.querySelector('#product-form');for(const[k,v]of Object.entries({id:'P02',name:'新商品',category:'分類',price:'200',stock:'3',image:'images/mug.jpg',sort_order:'2'}))f.elements[k].value=v;submit(w,'#product-form');await wait(()=>m.state.rows.length===2&&!d.querySelector('#editor').open);assert.equal(m.state.rows[1].is_active,false);d.querySelector('[data-edit="P01"]').click();f.elements.stock.value='9';submit(w,'#product-form');await wait(()=>m.state.rows[0].stock===9&&!d.querySelector('#editor').open);d.querySelector('[data-edit="P01"]').click();m.state.conflict=true;f.elements.stock.value='10';submit(w,'#product-form');await wait(()=>d.querySelector('#editor-status').textContent.includes('儲存未生效'));assert(d.querySelector('#editor').open);assert.equal(m.state.rows[0].stock,9);dom.window.close();
m=mock();m.state.user={id:'u2',email:'ordinary@example.test'};m.state.admin=false;dom=await setup('admin.html',m);await wait(()=>dom.window.document.querySelector('#admin-status').textContent.includes('尚未取得管理權限'));assert(dom.window.document.querySelector('#workspace').hidden);assert.equal(m.state.writes,0);dom.window.close();
m=mock();m.state.missing=true;dom=await setup('admin.html',m);await wait(()=>!dom.window.document.querySelector('#setup-panel').hidden);dom.window.close();
m=mock();m.state.rows[0].name='<img src=x onerror=alert(1)>';dom=await setup('index.html',m);w=dom.window;d=w.document;await wait(()=>d.querySelectorAll('.card').length===1);assert.equal(d.querySelector('.product-name').textContent,m.state.rows[0].name);assert.equal(d.querySelector('.product-name img'),null);assert.equal(d.querySelector('[data-shop-name]').textContent,'雲端商店');assert(d.querySelector('.demo').hidden);d.querySelector('[data-add]').click();d.querySelector('[data-add]').click();assert.equal(d.querySelector('#count').textContent,'2');m.state.rows[0].stock=1;m.state.rows[0].price=250;d.querySelector('#cart-top').click();await wait(()=>d.querySelector('#total').textContent==='NT$ 250');assert.equal(d.querySelector('#count').textContent,'1');assert(d.querySelector('#line').disabled);m.state.rows[0].is_active=false;d.querySelector('#refresh-products').click();await wait(()=>d.querySelector('#count').textContent==='0');assert.equal(d.querySelectorAll('.card').length,0);m.state.fail=true;d.querySelector('#refresh-products').click();await wait(()=>d.querySelector('#cloud-status').textContent.includes('載入失敗'));assert.equal(d.querySelectorAll('.card').length,0);dom.window.close();
m=mock();m.state.missing=true;dom=await setup('index.html',m);await wait(()=>dom.window.document.querySelectorAll('.card').length===6);assert(dom.window.document.querySelector('#cloud-status').textContent.includes('示範'));dom.window.close();
m=mock();m.state.settings.line_id='@demo';dom=await setup('index.html',m);w=dom.window;d=w.document;await wait(()=>d.querySelectorAll('.card').length===1);d.querySelector('[data-add]').click();let openedUrl='',closed=false;w.open=()=>({opener:w,close(){closed=true},location:{replace(url){openedUrl=url}}});d.querySelector('#line').click();await wait(()=>openedUrl.includes('line.me'));assert(openedUrl.includes('%40demo'));assert(decodeURIComponent(openedUrl).includes('測試商品'));openedUrl='';m.state.rows[0].stock=0;d.querySelector('#line').click();await wait(()=>closed);assert.equal(openedUrl,'');dom.window.close();
console.log('PASS: admin login gate, unauthorized user gate, product create/update, conflict preservation, setup state, frontend DB reading, XSS escaping, cart stock/price refresh, unlisting, network failure, demo fallback, LINE fresh-data guard');
